package ui

import (
	"errors"
	"fmt"
	"testing"
	"time"

	"github.com/ahhcash/llm-cli/session"
	"github.com/charmbracelet/bubbles/list"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/stretchr/testify/assert"
)

// Mock session.SwitchSession for testing purposes
var mockSwitchSession func(uuid string)

// Store original session.SwitchSession
var originalSwitchSession func(uuid string)

func setupSessionMocks() {
	originalSwitchSession = session.SwitchSession // Assuming session.SwitchSession is a global func or var
	mockSwitchSession = func(uuid string) {
		// No-op for testing, or can set a flag
	}
	session.SwitchSession = mockSwitchSession
}

func teardownSessionMocks() {
	session.SwitchSession = originalSwitchSession
}


func TestSessionModel_InitialState(t *testing.T) {
	model := NewSessionModel()
	assert.True(t, model.isLoading, "Model should be loading initially")
	
	cmd := model.Init()
	assert.NotNil(t, cmd, "Init should return a command to load sessions and tick spinner")

	// Check if it's a batch command (common for multiple initial actions)
	_, ok := cmd.(tea.BatchMsg)
	assert.True(t, ok, "Init command should be a BatchMsg")
}

func TestSessionModel_SessionsLoaded(t *testing.T) {
	model := NewSessionModel()
	
	sampleItems := []list.Item{
		sessionItem{SessionInfo: session.SessionInfo{UUID: "uuid1", MessageCount: 5, IsLatest: true, LastModified: time.Now()}},
		sessionItem{SessionInfo: session.SessionInfo{UUID: "uuid2", MessageCount: 10, IsLatest: false, LastModified: time.Now().Add(-time.Hour)}},
	}
	
	updatedModel, _ := model.Update(sessionsLoadedMsg{items: sampleItems})
	model = updatedModel.(sessionModel)

	assert.False(t, model.isLoading, "isLoading should be false after sessions are loaded")
	assert.Equal(t, len(sampleItems), len(model.list.Items()), "List should be populated with loaded items")
	assert.Contains(t, model.statusMessage, fmt.Sprintf("%d sessions loaded", len(sampleItems)), "Status message mismatch")
}

func TestSessionModel_SelectAndSwitchSession(t *testing.T) {
	setupSessionMocks()
	defer teardownSessionMocks()

	model := NewSessionModel()

	// 1. Load sessions
	sampleSessionItems := []list.Item{
		sessionItem{SessionInfo: session.SessionInfo{UUID: "test-uuid-1", MessageCount: 2, IsLatest: false, LastModified: time.Now()}},
		sessionItem{SessionInfo: session.SessionInfo{UUID: "test-uuid-2", MessageCount: 3, IsLatest: true, LastModified: time.Now()}},
	}
	updatedModel, _ := model.Update(sessionsLoadedMsg{items: sampleSessionItems})
	model = updatedModel.(sessionModel)
	
	// 2. Select the first item (index 0)
	model.list.Select(0) // This directly manipulates the list's internal state.

	// 3. Simulate pressing Enter
	updatedModel, cmdEnter := model.Update(tea.KeyMsg{Type: tea.KeyEnter})
	model = updatedModel.(sessionModel)

	assert.True(t, model.isLoading, "isLoading should be true during switch operation")
	assert.NotNil(t, cmdEnter, "Enter key should return a command for switching and spinner")
	assert.Contains(t, model.statusMessage, "Switching to test-uuid-1...", "Status message for switching is incorrect")


	// 4. Simulate the switchedSessionMsg that would be generated by the command
	//    This bypasses testing the command execution directly, which is complex for tea.Cmd funcs.
	updatedModel, cmdSwitch := model.Update(switchedSessionMsg{uuid: "test-uuid-1"})
	model = updatedModel.(sessionModel)
	
	assert.Contains(t, model.statusMessage, "Switched to session test-uuid-1.", "Status message after switching is incorrect")
	assert.Equal(t, tea.Quit, cmdSwitch, "Update after switchedSessionMsg should return tea.Quit")

}


func TestSessionModel_QuitMessages(t *testing.T) {
	model := NewSessionModel()

	// Test Ctrl+C
	updatedModel, cmdCtrlC := model.Update(tea.KeyMsg{Type: tea.KeyCtrlC})
	model = updatedModel.(sessionModel)
	assert.Equal(t, tea.Quit, cmdCtrlC, "Ctrl+C should return tea.Quit command")
	assert.Contains(t, model.statusMessage, "Session selection cancelled.", "Status message for quit is incorrect")


	// Test Esc
	model = NewSessionModel() // Reset model state
	updatedModel, cmdEsc := model.Update(tea.KeyMsg{Type: tea.KeyEsc})
	model = updatedModel.(sessionModel)
	assert.Equal(t, tea.Quit, cmdEsc, "Esc should return tea.Quit command")
	assert.Contains(t, model.statusMessage, "Session selection cancelled.", "Status message for quit is incorrect")
}

func TestSessionModel_ErrorMessage(t *testing.T) {
	model := NewSessionModel()
	model.isLoading = true // Simulate it was loading

	errMsgContent := "failed to load sessions"
	updatedModel, _ := model.Update(errorMsg{err: errors.New(errMsgContent)})
	model = updatedModel.(sessionModel)

	assert.False(t, model.isLoading, "isLoading should be false after an error")
	assert.Equal(t, errMsgContent, model.errorMessage, "Error message not set correctly in model")
}

func TestSessionModel_WindowResize(t *testing.T) {
	model := NewSessionModel()
	
	// Send an initial one to set it up and make model.ready true if that's a pattern
	model, _ = model.Update(tea.WindowSizeMsg{Width: 80, Height: 24})
	model = model.(sessionModel) // type assertion

	newWidth := 100
	newHeight := 30
	updatedModel, _ := model.Update(tea.WindowSizeMsg{Width: newWidth, Height: newHeight})
	model = updatedModel.(sessionModel)

	// Check if list dimensions are updated.
	// The list sets its size considering padding and other elements.
	// Exact calculation depends on appStyle, titleStyle, helpStyle heights.
	// For simplicity, just check that width has changed. A more robust test would calculate expected values.
	currentListWidth, _ := model.list.Size()
	assert.NotEqual(t, 80-appStyle.GetHorizontalPadding(), currentListWidth, "List width should have been updated by WindowSizeMsg")
	assert.Equal(t, newWidth-appStyle.GetHorizontalPadding(), currentListWidth, "List width not correctly set after resize")
}

// Note: Testing loadSessionsCmd directly is possible but would require
// the session files to be present or mocked. The current tests focus on
// how the model *reacts* to the messages produced by such commands.
[end of ui/session_tui_test.go]
